options:
  sftp-config:
    type: string
    default: ""
    description: "user,path:name,path:name;user,path:name,path:name"
  sftp-chown-mnt:
    type: boolean
    default: True
    description: "Chown to the user after mounting into the chroot"
  sftp-password-auth:
    type: boolean
    default: True
    description: "Allow password authentication"
